DROP TABLE IF EXISTS item_entrega CASCADE;
DROP TABLE IF EXISTS entrega CASCADE;
DROP TABLE IF EXISTS produto CASCADE;
DROP TABLE IF EXISTS cliente CASCADE;
DROP TABLE IF EXISTS endereco CASCADE;


CREATE TABLE endereco (
    id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rua     VARCHAR(150) NOT NULL,
    numero  VARCHAR(20)  NOT NULL,
    bairro  VARCHAR(100) NOT NULL,
    cidade  VARCHAR(100) NOT NULL,
    estado  VARCHAR(50)  NOT NULL,
    cep     VARCHAR(10)  NOT NULL
);


CREATE TABLE produto (
    id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(30)    NOT NULL UNIQUE,
    nome   VARCHAR(150)   NOT NULL,
    peso   DECIMAL(10, 3) NOT NULL CHECK (peso > 0),
    volume DECIMAL(10, 3) NOT NULL CHECK (volume > 0),
    valor  DECIMAL(12, 2) NOT NULL CHECK (valor > 0)
);10


CREATE TABLE cliente (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(150) NOT NULL,
    telefone    VARCHAR(20)  NOT NULL,
    documento   VARCHAR(18)  NOT NULL UNIQUE,
    endereco_id INT          NOT NULL,
    CONSTRAINT fk_cliente_endereco
        FOREIGN KEY (endereco_id) REFERENCES endereco (id)
);


CREATE TABLE entrega (
   id                   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   codigo               VARCHAR(30) NOT NULL UNIQUE,
   remetente_id         INT         NOT NULL,
   destinatario_id      INT         NOT NULL,
   endereco_origem_id   INT         NOT NULL,
   endereco_destino_id  INT         NOT NULL,
   status               VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
   CONSTRAINT ck_entrega_status
       CHECK (status IN ('PENDENTE', 'REALIZADA', 'NAO_REALIZADA')),
   CONSTRAINT fk_entrega_remetente
       FOREIGN KEY (remetente_id) REFERENCES cliente (id),
   CONSTRAINT fk_entrega_destinatario
       FOREIGN KEY (destinatario_id) REFERENCES cliente (id),
   CONSTRAINT fk_entrega_origem
       FOREIGN KEY (endereco_origem_id) REFERENCES endereco (id),
   CONSTRAINT fk_entrega_destino
       FOREIGN KEY (endereco_destino_id) REFERENCES endereco (id)
);


CREATE TABLE item_entrega (
   id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   entrega_id INT NOT NULL,
   produto_id INT NOT NULL,
   quantidade INT NOT NULL CHECK (quantidade >= 1

   
   CONSTRAINT uq_item_entrega_produto UNIQUE (entrega_id, produto_id),
   CONSTRAINT fk_item_entrega_entrega
       FOREIGN KEY (entrega_id) REFERENCES entrega (id) ON DELETE CASCADE,
   CONSTRAINT fk_item_entrega_produto
       FOREIGN KEY (produto_id) REFERENCES produto (id)
);

